to:
  image: schmunk42/nginx-redirect
  ports:
    - "8888:80"
  environment:
    - SERVER_REDIRECT=www.example.com
    # optionally define path to redirect all requests
    # if not set nginx var  is used
    #- SERVER_REDIRECT_PATH=/landingpage
