to:
  image: schmunk42/nginx-redirect
  ports:
    - "8888:80"
  environment:
    - SERVER_REDIRECT=www.example.com
    # optionally define path to redirect all requests
    # if not set nginx var $request_uri is used
    #- SERVER_REDIRECT_PATH=/landingpage
    # optionally define schema to redirect all requests
    # if not set but X-Forwarded-Proto is send as request header with value 'https' this will be used.
    # In all other cases nginx var `$scheme` is used
    #- SERVER_REDIRECT_SCHEME=https
    # optionally define the http code to use for redirection
    # allowed Codes are: 301, 302, 303, 307, 308, default is 301
    #- SERVER_REDIRECT_CODE=301
    # optionally define the http code to redirect POST requests
    # if not set or not in allowed Codes, SERVER_REDIRECT_CODE will be used
    #- SERVER_REDIRECT_POST_CODE=
    # optionally define the location for the nginx access log
    # if not set /dev/stdout is used
    #- SERVER_ACCESS_LOG=/dev/null
    # optionally define the location for the nginx error log
    # if not set /dev/stderr is used
    #- SERVER_ERROR_LOG=/dev/null
